import { GraphQLEnumType } from 'graphql';

const CriminalProfileSortByEnumType = new GraphQLEnumType({
  name: 'CriminalProfileSortByEnumType',
  values: {
    id: { value: 'id' },
    alias: { value: 'alias' },
    name: { value: 'name' },
    surname: { value: 'surname' },
    fullName: { value: 'fullName' },
    relationType: { value: 'relationType' },
    relativeName: { value: 'relativeName' },
    gender: { value: 'gender' },
    isDied: { value: 'isDied' },
    dateOfBirth: { value: 'dateOfBirth' },
    age: { value: 'age' },
    occupation: { value: 'occupation' },
    educationQualification: { value: 'educationQualification' },
    domicile: { value: 'domicile' },
    caste: { value: 'caste' },
    subCaste: { value: 'subCaste' },
    religion: { value: 'religion' },
    nationality: { value: 'nationality' },
    designation: { value: 'designation' },
    placeOfWork: { value: 'placeOfWork' },
    presentHouseNo: { value: 'presentHouseNo' },
    presentStreetRoadNo: { value: 'presentStreetRoadNo' },
    presentWardColony: { value: 'presentWardColony' },
    presentLandmarkMilestone: { value: 'presentLandmarkMilestone' },
    presentLocalityVillage: { value: 'presentLocalityVillage' },
    presentAreaMandal: { value: 'presentAreaMandal' },
    presentDistrict: { value: 'presentDistrict' },
    presentStateUt: { value: 'presentStateUt' },
    presentCountry: { value: 'presentCountry' },
    presentResidencyType: { value: 'presentResidencyType' },
    presentPinCode: { value: 'presentPinCode' },
    presentJurisdictionPs: { value: 'presentJurisdictionPs' },
    permanentHouseNo: { value: 'permanentHouseNo' },
    permanentStreetRoadNo: { value: 'permanentStreetRoadNo' },
    permanentWardColony: { value: 'permanentWardColony' },
    permanentLandmarkMilestone: { value: 'permanentLandmarkMilestone' },
    permanentLocalityVillage: { value: 'permanentLocalityVillage' },
    permanentAreaMandal: { value: 'permanentAreaMandal' },
    permanentDistrict: { value: 'permanentDistrict' },
    permanentStateUt: { value: 'permanentStateUt' },
    permanentCountry: { value: 'permanentCountry' },
    permanentResidencyType: { value: 'permanentResidencyType' },
    permanentPinCode: { value: 'permanentPinCode' },
    permanentJurisdictionPs: { value: 'permanentJurisdictionPs' },
    phoneNumber: { value: 'phoneNumber' },
    countryCode: { value: 'countryCode' },
    emailId: { value: 'emailId' },
    identityDocuments: { value: 'identityDocuments' },
    documents: { value: 'documents' },
    crimes: { value: 'crimes' },
    associatedDrugs: { value: 'associatedDrugs' },
    latestCrimeNo: { value: 'latestCrimeNo' },
    noOfCrimes: { value: 'noOfCrimes' },
    arrestCount: { value: 'arrestCount' },
    previouslyInvolvedCases: { value: 'previouslyInvolvedCases' },
    DOPAMSLinks: { value: 'DOPAMSLinks' },
    counselled: { value: 'counselled' },
    socialMedia: { value: 'socialMedia' },
    RTAData: { value: 'RTAData' },
    bankAcountDetails: { value: 'bankAcountDetails' },
    passportDetails_Foreigners: { value: 'passportDetails_Foreigners' },
    purposeOfVISA_Foreigners: { value: 'purposeOfVISA_Foreigners' },
    validityOfVISA_Foreigners: { value: 'validityOfVISA_Foreigners' },
    localaddress_Foreigners: { value: 'localaddress_Foreigners' },
    nativeAddress_Foreigners: { value: 'nativeAddress_Foreigners' },
    statusOfTheAccused: { value: 'statusOfTheAccused' },
    historySheet: { value: 'historySheet' },
    propertyForfeited: { value: 'propertyForfeited' },
    PITNDPSInitiated: { value: 'PITNDPSInitiated' },
    photo: { value: 'photo' },
  },
});

export default CriminalProfileSortByEnumType;
