import { GraphQLEnumType } from 'graphql';

const AccusedSortByEnumType = new GraphQLEnumType({
  name: 'AccusedSortByEnumType',
  values: {
    id: { value: 'id' },
    unit: { value: 'unit' },
    ps: { value: 'ps' },
    year: { value: 'year' },
    crimeId: { value: 'crimeId' },
    personId: { value: 'personId' },
    firNumber: { value: 'firNumber' },
    firRegNum: { value: 'firRegNum' },
    section: { value: 'section' },
    crimeRegDate: { value: 'crimeRegDate' },
    briefFacts: { value: 'briefFacts' },
    accusedCode: { value: 'accusedCode' },
    seqNum: { value: 'seqNum' },
    isCCL: { value: 'isCCL' },
    beard: { value: 'beard' },
    build: { value: 'build' },
    color: { value: 'color' },
    ear: { value: 'ear' },
    eyes: { value: 'eyes' },
    face: { value: 'face' },
    hair: { value: 'hair' },
    height: { value: 'height' },
    leucoderma: { value: 'leucoderma' },
    mole: { value: 'mole' },
    mustache: { value: 'mustache' },
    nose: { value: 'nose' },
    teeth: { value: 'teeth' },
    accusedStatus: { value: 'accusedStatus' },
    // NEW: raw un-normalized status string
    accusedStatusRaw: { value: 'accusedStatusRaw' },
    accusedType: { value: 'accusedType' },
    // NEW: role in crime (peddler, supplier, etc.) from brief_facts_accused
    accusedRole: { value: 'accusedRole' },
    noOfAccusedInvolved: { value: 'noOfAccusedInvolved' },
    accusedDetails: { value: 'accusedDetails' },
    parentage: { value: 'parentage' },
    relationType: { value: 'relationType' },
    gender: { value: 'gender' },
    isDied: { value: 'isDied' },
    dateOfBirth: { value: 'dateOfBirth' },
    age: { value: 'age' },
    // NEW: domicile classification (Local/Outsider/Foreign) is now a direct column in the MV
    domicile: { value: 'domicile' },
    occupation: { value: 'occupation' },
    educationQualification: { value: 'educationQualification' },
    caste: { value: 'caste' },
    subCaste: { value: 'subCaste' },
    religion: { value: 'religion' },
    nationality: { value: 'nationality' },
    designation: { value: 'designation' },
    placeOfWork: { value: 'placeOfWork' },
    presentHouseNo: { value: 'presentHouseNo' },
    presentStreetRoadNo: { value: 'presentStreetRoadNo' },
    presentWardColony: { value: 'presentWardColony' },
    presentLandmarkMilestone: { value: 'presentLandmarkMilestone' },
    presentLocalityVillage: { value: 'presentLocalityVillage' },
    presentAreaMandal: { value: 'presentAreaMandal' },
    presentDistrict: { value: 'presentDistrict' },
    presentStateUt: { value: 'presentStateUt' },
    presentCountry: { value: 'presentCountry' },
    presentResidencyType: { value: 'presentResidencyType' },
    presentPinCode: { value: 'presentPinCode' },
    presentJurisdictionPs: { value: 'presentJurisdictionPs' },
    permanentHouseNo: { value: 'permanentHouseNo' },
    permanentStreetRoadNo: { value: 'permanentStreetRoadNo' },
    permanentWardColony: { value: 'permanentWardColony' },
    permanentLandmarkMilestone: { value: 'permanentLandmarkMilestone' },
    permanentLocalityVillage: { value: 'permanentLocalityVillage' },
    permanentAreaMandal: { value: 'permanentAreaMandal' },
    permanentDistrict: { value: 'permanentDistrict' },
    permanentStateUt: { value: 'permanentStateUt' },
    permanentCountry: { value: 'permanentCountry' },
    permanentResidencyType: { value: 'permanentResidencyType' },
    permanentPinCode: { value: 'permanentPinCode' },
    permanentJurisdictionPs: { value: 'permanentJurisdictionPs' },
    phoneNumber: { value: 'phoneNumber' },
    countryCode: { value: 'countryCode' },
    emailId: { value: 'emailId' },
    noOfCrimes: { value: 'noOfCrimes' },
    previouslyInvolvedCases: { value: 'previouslyInvolvedCases' },
    drugWithQuantity: { value: 'drugWithQuantity' },
    caseClassification: { value: 'caseClassification' },
    caseStatus: { value: 'caseStatus' },
  },
});

export default AccusedSortByEnumType;
