import { GraphQLObjectType, GraphQLString } from 'graphql';

export const SuspectType = new GraphQLObjectType({
  name: 'SuspectType',
  fields: () => ({
    accused_no: { type: GraphQLString },
    full_name: { type: GraphQLString },
    alias: { type: GraphQLString },
    parentage: { type: GraphQLString },
    age: { type: GraphQLString },
    h_no: { type: GraphQLString },
    locality: { type: GraphQLString },
    area: { type: GraphQLString },
    person_ps: { type: GraphQLString },
    person_district: { type: GraphQLString },
    person_state: { type: GraphQLString },
    person_country: { type: GraphQLString },
    accu_bank_account: { type: GraphQLString },
    accu_bank_name: { type: GraphQLString },
    accu_bank_state: { type: GraphQLString },
    accu_bank_district: { type: GraphQLString },
    accu_email: { type: GraphQLString },
    accu_facebook: { type: GraphQLString },
    accu_other_social_media: { type: GraphQLString },
    remarks: { type: GraphQLString },
    accu_crtd_date: { type: GraphQLString },
    accu_mdfd_date: { type: GraphQLString },
    accu_crtd_user: { type: GraphQLString },
    accu_mdfd_user: { type: GraphQLString },
    accu_otp_code: { type: GraphQLString },
    module: { type: GraphQLString },
    gender: { type: GraphQLString },
    aadhar_no: { type: GraphQLString },
    passport_no: { type: GraphQLString },
    h_no_t: { type: GraphQLString },
    locality_t: { type: GraphQLString },
    area_t: { type: GraphQLString },
    person_ps_t: { type: GraphQLString },
    person_district_t: { type: GraphQLString },
    person_state_t: { type: GraphQLString },
    person_country_t: { type: GraphQLString },
    lat: { type: GraphQLString },
    long: { type: GraphQLString },
    lat_t: { type: GraphQLString },
    long_t: { type: GraphQLString },
    wallet_info: { type: GraphQLString },
    source: { type: GraphQLString },
    mondal: { type: GraphQLString },
    datebirth: { type: GraphQLString },
    occupation: { type: GraphQLString },
    voterid: { type: GraphQLString },
    drivingl: { type: GraphQLString },
    education: { type: GraphQLString },
    languages: { type: GraphQLString },
    statevisit: { type: GraphQLString },
    bank_ifsc: { type: GraphQLString },
    wallet_name: { type: GraphQLString },
    wallet_id: { type: GraphQLString },
    countryvisit: { type: GraphQLString },
    mondal2: { type: GraphQLString },
    fir_reg_num: { type: GraphQLString },
    photo_status: { type: GraphQLString },
    person_type: { type: GraphQLString },
    pd_act__: { type: GraphQLString },
  }),
});
