import { GraphQLEnumType } from 'graphql';

const AdvancedSearchColumnEnumType = new GraphQLEnumType({
  name: 'AdvancedSearchColumnEnumType',
  values: {
    // crimes table
    id: { value: 'id' },
    psCode: { value: 'psCode' },
    firNum: { value: 'firNum' },
    firRegNum: { value: 'firRegNum' },
    firType: { value: 'firType' },
    sections: { value: 'sections' },
    firDate: { value: 'firDate' },
    caseClass: { value: 'caseClass' },
    caseStatus: { value: 'caseStatus' },
    stipulatedPeriodForCS: { value: 'stipulatedPeriodForCS' },
    majorHead: { value: 'majorHead' },
    minorHead: { value: 'minorHead' },
    crimeType: { value: 'crimeType' },
    ioName: { value: 'ioName' },
    ioRank: { value: 'ioRank' },
    briefFacts: { value: 'briefFacts' },

    // accused table
    accusedCode: { value: 'accusedCode' },
    type: { value: 'type' },
    seqNum: { value: 'seqNum' },
    isCCL: { value: 'isCCL' },
    beard: { value: 'beard' },
    build: { value: 'build' },
    color: { value: 'color' },
    ear: { value: 'ear' },
    eyes: { value: 'eyes' },
    face: { value: 'face' },
    hair: { value: 'hair' },
    height: { value: 'height' },
    leucoderma: { value: 'leucoderma' },
    mole: { value: 'mole' },
    mustache: { value: 'mustache' },
    nose: { value: 'nose' },
    teeth: { value: 'teeth' },

    // brief_facts_accused table
    accusedType: { value: 'accusedType' },
    accusedStatus: { value: 'accusedStatus' },

    // brief_facts_drugs table
    drugType: { value: 'drugType' },
    drugQuantityKg: { value: 'drugQuantityKg' },
    drugQuantityMl: { value: 'drugQuantityMl' },
    drugQuantityCount: { value: 'drugQuantityCount' },
    drugWorth: { value: 'drugWorth' },

    // heirarchy table
    psName: { value: 'psName' },
    circleCode: { value: 'circleCode' },
    circleName: { value: 'circleName' },
    sdpoCode: { value: 'sdpoCode' },
    sdpoName: { value: 'sdpoName' },
    subZoneCode: { value: 'subZoneCode' },
    subZoneName: { value: 'subZoneName' },
    distCode: { value: 'distCode' },
    distName: { value: 'distName' },
    rangeCode: { value: 'rangeCode' },
    rangeName: { value: 'rangeName' },
    zoneCode: { value: 'zoneCode' },
    zoneName: { value: 'zoneName' },
    adgCode: { value: 'adgCode' },
    adgName: { value: 'adgName' },

    // person table
    name: { value: 'name' },
    surname: { value: 'surname' },
    alias: { value: 'alias' },
    fullName: { value: 'fullName' },
    relationType: { value: 'relationType' },
    relativeName: { value: 'relativeName' },
    gender: { value: 'gender' },
    isDied: { value: 'isDied' },
    dateOfBirth: { value: 'dateOfBirth' },
    age: { value: 'age' },
    occupation: { value: 'occupation' },
    educationQualification: { value: 'educationQualification' },
    caste: { value: 'caste' },
    subCaste: { value: 'subCaste' },
    religion: { value: 'religion' },
    domicile: { value: 'domicile' },
    nationality: { value: 'nationality' },
    designation: { value: 'designation' },
    placeOfWork: { value: 'placeOfWork' },
    presentHouseNo: { value: 'presentHouseNo' },
    presentStreetRoadNo: { value: 'presentStreetRoadNo' },
    presentWardColony: { value: 'presentWardColony' },
    presentLandmarkMilestone: { value: 'presentLandmarkMilestone' },
    presentLocalityVillage: { value: 'presentLocalityVillage' },
    presentAreaMandal: { value: 'presentAreaMandal' },
    presentDistrict: { value: 'presentDistrict' },
    presentStateUt: { value: 'presentStateUt' },
    presentCountry: { value: 'presentCountry' },
    presentResidencyType: { value: 'presentResidencyType' },
    presentPinCode: { value: 'presentPinCode' },
    presentJurisdictionPs: { value: 'presentJurisdictionPs' },
    presentAddress: { value: 'presentAddress' },
    permanentHouseNo: { value: 'permanentHouseNo' },
    permanentStreetRoadNo: { value: 'permanentStreetRoadNo' },
    permanentWardColony: { value: 'permanentWardColony' },
    permanentLandmarkMilestone: { value: 'permanentLandmarkMilestone' },
    permanentLocalityVillage: { value: 'permanentLocalityVillage' },
    permanentAreaMandal: { value: 'permanentAreaMandal' },
    permanentDistrict: { value: 'permanentDistrict' },
    permanentStateUt: { value: 'permanentStateUt' },
    permanentCountry: { value: 'permanentCountry' },
    permanentResidencyType: { value: 'permanentResidencyType' },
    permanentPinCode: { value: 'permanentPinCode' },
    permanentJurisdictionPs: { value: 'permanentJurisdictionPs' },
    permanentAddress: { value: 'permanentAddress' },
    phoneNumber: { value: 'phoneNumber' },
    countryCode: { value: 'countryCode' },
    emailId: { value: 'emailId' },
  },
});

export default AdvancedSearchColumnEnumType;
